name: CodeQL

on:
  push:
    branches: [ backend ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'typescript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      run: |
        cd notes-app
        npm install
        npm run build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
